name: Build Apps

on:
  workflow_dispatch:
  workflow_call:
    outputs:
      run_id:
        description: "Run ID"
        value: ${{ github.run_id }}
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_linux:
    runs-on: ubuntu-20.04

    env:
      extractorDir: ./DataExtractor

    steps:
    - uses: actions/checkout@v4

    - name: make
      working-directory: ${{env.extractorDir}}
      run: make

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: CompileScore-Extractor-Linux
        path: ${{env.extractorDir}}/bin/make/ScoreDataExtractor

  build_macos:
    runs-on: macos-latest

    env:
      extractorDir: ./DataExtractor

    steps:
    - uses: actions/checkout@v4

    - name: make
      working-directory: ${{env.extractorDir}}
      run: make

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: CompileScore-Extractor-MacOS
        path: ${{env.extractorDir}}/bin/make/ScoreDataExtractor

  build_windows:
    runs-on: windows-latest

    env:
      extractorDir: ./DataExtractor
      parserDir: ./Parser
      appsDir: ./CompileScore
      extractorSolution: ScoreDataExtractor.sln
      parserSolution: CompileScoreParser.sln
      appsSolution: CompileScore.sln
      toolsBuildConfig: Release
      NetPlatform: net7.0-windows

    strategy:
      matrix:
        buildconfig: [Release]

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Checkout LLVM library
      uses: actions/checkout@v4
      with:
        repository: Viladoman/ClangArtifacts
        sparse-checkout: llvm-project
        path: External

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1

    - uses: nuget/setup-nuget@v1
      with:
        nuget-version: '5.x'

    - name: NuGet restore Score Data Extractor
      working-directory: ${{env.extractorDir}}
      run: nuget restore ${{ env.extractorSolution }}

    - name: Build Score Data Extractor
      working-directory: ${{env.extractorDir}}
      run: msbuild /m /p:Configuration=${{ matrix.buildconfig }} /p:Platform=x64 ${{ env.extractorSolution }}

    - name: Build Parser
      working-directory: ${{env.parserDir}}
      run: msbuild /m /p:Configuration=${{ env.toolsBuildConfig }} /p:Platform=x64 ${{ env.parserSolution }}

    - name: NuGet restore Compile Score
      working-directory: ${{env.appsDir}}
      run: nuget restore ${{ env.appsSolutionName }}

    - name: Build Compile Score VSIX
      working-directory: ${{env.appsDir}}
      run: msbuild /m /p:Configuration=${{matrix.buildconfig}} ${{ env.appsSolutionName }}

    - name: Upload Extractor Artifacts (Executable)
      if: ${{matrix.buildconfig == env.toolsBuildConfig}}
      uses: actions/upload-artifact@v4
      with:
        name: CompileScore-Extractor-Windows-Executable
        path: ${{env.extractorDir}}/bin/x64/${{matrix.buildconfig}}/*.exe

    - name: Upload Extractor Artifacts (Libraries)
      if: ${{matrix.buildconfig == env.toolsBuildConfig}}
      uses: actions/upload-artifact@v4
      with:
        name: CompileScore-Extractor-Windows-Libraries
        path: ${{env.extractorDir}}/bin/x64/${{matrix.buildconfig}}/*.dll

    - name: Upload Parser Artifact
      if: ${{matrix.buildconfig == env.toolsBuildConfig}}
      uses: actions/upload-artifact@v4
      with:
        name: CompileScore-Parser-${{env.toolsBuildConfig}}
        path: ${{env.parserDir}}/bin/x64/${{env.toolsBuildConfig}}/CompileScoreParser.exe

    - name: Upload VSIX 2019 Extension Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: CompileScore-VSIX2019-${{matrix.buildconfig}}
        path: ${{env.appsDir}}/VSIX16/bin/${{matrix.buildconfig}}/CompileScore.vsix

    - name: Upload VSIX 2022 Extension Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: CompileScore-VSIX2022-${{matrix.buildconfig}}
        path: ${{env.appsDir}}/VSIX17/bin/${{matrix.buildconfig}}/CompileScore.vsix

    - name: Upload App Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: CompileScore-App-${{matrix.buildconfig}}
        path: ${{env.appsDir}}/WPF/bin/${{matrix.buildconfig}}/${{ env.NetPlatform }}/*
