name: Data Extractor All

on:
  workflow_dispatch: {}
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_linux:
    runs-on: ubuntu-20.04

    env:
      extractorDir: ./DataExtractor

    steps:
    - uses: actions/checkout@v4

    - name: make
      working-directory: ${{env.extractorDir}}
      run: make

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: CompileScore-Extractor-Linux
        path: ${{env.extractorDir}}/bin/make/ScoreDataExtractor

  build_macos:
    runs-on: macos-latest

    env:
      extractorDir: ./DataExtractor

    steps:
    - uses: actions/checkout@v4

    - name: make
      working-directory: ${{env.extractorDir}}
      run: make

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: CompileScore-Extractor-MacOS
        path: ${{env.extractorDir}}/bin/make/ScoreDataExtractor

  build_windows:
    runs-on: windows-latest

    env:
      baseDir: ./DataExtractor
      solutionName: ScoreDataExtractor.sln

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1

    - uses: nuget/setup-nuget@v1
      with:
        nuget-version: '5.x'

    - name: NuGet restore
      working-directory: ${{env.baseDir}}
      run: nuget restore ${{ env.solutionName }}

    - name: Build Score Data Extractor
      working-directory: ${{env.baseDir}}
      run: msbuild /m /p:Configuration=Release /p:Platform=x64 ${{ env.solutionName }}

    - name: Upload Artifacts (Executable)
      uses: actions/upload-artifact@v4
      with:
        name: CompileScore-Extractor-Windows
        path: ${{env.baseDir}}/bin/x64/Release/*.exe

    - name: Upload Artifacts (Libraries)
      uses: actions/upload-artifact@v4
      with:
        name: CompileScore-Extractor-Windows
        path: ${{env.baseDir}}/bin/x64/Release/*.dll
